import { jsPDF } from "jspdf";

import { formatEventDate } from "@/lib/format";
import { getEventStatusLabel } from "@/lib/event-status";
import type { EventRecord } from "@/lib/types";

export function exportEventPdf(event: EventRecord): void {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(event.name, margin, y);
  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Status: ${getEventStatusLabel(event.status)}`, margin, y);
  y += 8;
  doc.text(`Date: ${formatEventDate(event.date)}`, margin, y);
  y += 8;
  doc.text(`Attendees: ${event.attendeeCount}`, margin, y);
  y += 14;

  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Speaker", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(event.speakerName, margin, y);
  y += 7;
  doc.text(event.speakerDesignation, margin, y);
  y += 14;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text("Generated by Onference Event Studio", margin, 285);

  doc.save(`${event.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-event.pdf`);
}
